### ISSUE TITLE
곡 자켓 이미지 누락

### ISSUE THREAD

**Issue by chlwnsgud7** [pumgall/pumgall.github.io#1]
324 Bring Back The Beat
325 Break Out
둘 다 Lunatic Sound의 곡입니다.

펌프공홈에도 이 두 자켓 이미지가 빠져있어서 생기는 문제같습니다.

**Comment by chlwnsgud7** [comment]
Prime2 공식 홈페이지에 이미지가 있기는 한데, 종횡비가 XX와는 다릅니다. 그마저도 브링 백 더 비트는 펌프잇업 공식 홈페이지에서는 제공하고 있지 않습니다.
저 같은 경우는 일어 위키에서 찾아오는 것으로 해결했었습니다.
https://image02.seesaawiki.jp/p/n/piujpn/b4fc8551317c619a.png
http://www.piugame.com/piu.prime2/prime2.songImg/538.png

**Comment by daebo01** [comment]
제보 감사합니다.
말씀 주신 2개의 이미지 수정하였습니다.
:blush:
